# Copyright 2021 ETH Zurich and the HPCAgent-Bench authors.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Every agent harness in the judge-agent images installs from a checked-in pin.

An unpinned install caches on the command string and ages onto whatever the first build pulled, so
two images built weeks apart run different agents under one arm name. The pins live in
containers/agent/harness: pins.env (uv, node, the harness python), node/package.json with its lock
(the npm CLIs) and requirements-<name>.txt (one full freeze per Python harness), all regenerated by
freeze.sh. Static: the checks read files, nothing is fetched.
"""

import json
import pathlib
import re

import pytest

ROOT: pathlib.Path = pathlib.Path(__file__).resolve().parents[1]
HARNESS: pathlib.Path = ROOT / "containers" / "agent" / "harness"
CE_IMAGES: pathlib.Path = ROOT / "containers" / "cluster" / "ce-images"
JUDGE_AGENT_DOCKERFILES: tuple[str, ...] = ("judge-agent-amd/Dockerfile", "judge-agent-cuda/Dockerfile")
IMAGE_DOCKERFILES: tuple[str, ...] = tuple(
    sorted(str(path.relative_to(CE_IMAGES)) for path in CE_IMAGES.rglob("Dockerfile"))
)

#: Every recorded claude arm ran this CLI.
CLAUDE_CODE_VERSION: str = "2.1.197"
#: Python harness venv -> the import its image gate runs: every module its runner imports.
PYTHON_HARNESSES: dict[str, str] = {
    "miniswe": (
        "import yaml, minisweagent.agents.default, minisweagent.environments.local, minisweagent.models.litellm_model"
    ),
    "openhands": (
        "import openhands.sdk.event.conversation_error, openhands.tools.file_editor, openhands.tools.preset.default, "
        "openhands.tools.terminal"
    ),
    "sweagent": "import sweagent",
}
REQUIREMENT_NAMES: tuple[str, ...] = tuple(
    sorted(path.stem.removeprefix("requirements-") for path in HARNESS.glob("requirements-*.txt"))
)
#: npm packages whose CLI is a per-platform native binary package, as <prefix>-linux-<arch>.
NATIVE_BINARY_PREFIXES: tuple[str, ...] = ("@anthropic-ai/claude-code", "@openai/codex", "opencode")
#: npm cpu names of the two image architectures: judge-agent-amd x86_64, judge-agent-cuda aarch64.
IMAGE_NPM_ARCHES: tuple[str, ...] = ("x64", "arm64")
PINS_ENV_SHAPES: dict[str, str] = {
    "HARNESS_PYTHON": r"3\.\d+",
    "UV_VERSION": r"\d+\.\d+\.\d+",
    "UV_SHA256_X86_64": r"[0-9a-f]{64}",
    "UV_SHA256_AARCH64": r"[0-9a-f]{64}",
    "NODE_VERSION": r"\d+\.\d+\.\d+",
    "NODE_SHA256_X64": r"[0-9a-f]{64}",
    "NODE_SHA256_ARM64": r"[0-9a-f]{64}",
}

EXACT_VERSION: re.Pattern[str] = re.compile(r"\d+\.\d+\.\d+")
EXACT_NPM_SPEC: re.Pattern[str] = re.compile(r"(?:@[^/\s]+/)?[^@\s]+@\d+\.\d+\.\d+")
FREEZE_PIN: re.Pattern[str] = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*==[0-9][A-Za-z0-9.+!-]*")
GIT_PIN: re.Pattern[str] = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]* @ git\+https://[^@\s]+@[0-9a-f]{40}")
SWEAGENT_PIN: re.Pattern[str] = re.compile(r"sweagent @ git\+https://github\.com/SWE-agent/SWE-agent@[0-9a-f]{40}")
UNPINNED_FETCHES: tuple[re.Pattern[str], ...] = (re.compile(r"releases/latest"), re.compile(r"setup_\d+\.x"))
NPM_GLOBAL_INSTALL: re.Pattern[str] = re.compile(r"npm\s+(?:install|i)\s+(?:-g|--global)\s+([^;&|\\\n]+)")


def json_object(value: object, where: str) -> dict[str, object]:
    assert isinstance(value, dict), f"{where} is not a JSON object"
    return {str(key): member for key, member in value.items()}


def dependencies() -> dict[str, str]:
    package = json_object(json.loads((HARNESS / "node" / "package.json").read_text(encoding="utf-8")), "package.json")
    return {name: str(version) for name, version in json_object(package["dependencies"], "dependencies").items()}


def locked_packages() -> dict[str, dict[str, object]]:
    lock = json_object(json.loads((HARNESS / "node" / "package-lock.json").read_text(encoding="utf-8")), "lock")
    packages = json_object(lock["packages"], "packages")
    return {path: json_object(meta, path) for path, meta in packages.items()}


def pins_env() -> dict[str, str]:
    pins: dict[str, str] = {}
    for line in (HARNESS / "pins.env").read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#"):
            key, sep, value = line.partition("=")
            assert sep, f"pins.env line is not KEY=VALUE: {line!r}"
            pins[key] = value
    return pins


def pinned_lines(name: str) -> list[str]:
    text = (HARNESS / f"requirements-{name}.txt").read_text(encoding="utf-8")
    return [line for line in text.splitlines() if line.strip() and not line.startswith("#")]


def recipe(dockerfile: str) -> str:
    return (CE_IMAGES / dockerfile).read_text(encoding="utf-8")


def unpinned_installs(text: str) -> list[str]:
    """Each fetch in a recipe that resolves to whatever upstream publishes on the day it runs."""
    found = [pattern.pattern for pattern in UNPINNED_FETCHES if pattern.search(text)]
    for match in NPM_GLOBAL_INSTALL.finditer(text):
        for token in match.group(1).split():
            spec = token.strip("\"'")
            if not spec.startswith("-") and EXACT_NPM_SPEC.fullmatch(spec) is None:
                found.append(spec)
    return found


@pytest.mark.parametrize("package", sorted(dependencies()))
def test_every_npm_cli_is_pinned_to_an_exact_version(package: str) -> None:
    """A range lets the lock move to a different CLI the next time anyone regenerates it."""
    version = dependencies()[package]
    assert EXACT_VERSION.fullmatch(version), f"{package} is pinned as {version!r}, not an exact version"


def test_claude_code_is_the_version_every_recorded_claude_arm_ran() -> None:
    assert dependencies()["@anthropic-ai/claude-code"] == CLAUDE_CODE_VERSION


def test_the_npm_lock_was_generated_from_package_json() -> None:
    """npm ci rejects a lock that disagrees with package.json, but only at build time, hours in."""
    packages = locked_packages()
    assert packages[""]["dependencies"] == dependencies(), packages[""]["dependencies"]
    locked = {name: packages[f"node_modules/{name}"]["version"] for name in dependencies()}
    assert locked == dependencies(), locked


def test_every_locked_npm_package_is_a_registry_tarball_with_its_integrity() -> None:
    floating = [
        path
        for path, meta in locked_packages().items()
        if path
        and not (
            str(meta.get("resolved", "")).startswith("https://registry.npmjs.org/")
            and str(meta.get("integrity", "")).startswith("sha512-")
        )
    ]
    assert floating == [], floating


@pytest.mark.parametrize("arch", IMAGE_NPM_ARCHES)
@pytest.mark.parametrize("prefix", NATIVE_BINARY_PREFIXES)
def test_the_npm_lock_carries_each_native_cli_binary_for_both_image_architectures(prefix: str, arch: str) -> None:
    """Both images npm ci from one lock; a lock missing the arm64 binary builds a CUDA image with no CLI."""
    meta = locked_packages().get(f"node_modules/{prefix}-linux-{arch}")
    assert meta is not None, f"package-lock.json has no {prefix}-linux-{arch}"
    assert (meta.get("os"), meta.get("cpu")) == (["linux"], [arch]), meta


@pytest.mark.parametrize("key", sorted(PINS_ENV_SHAPES))
def test_pins_env_names_an_exact_tool_version_or_checksum(key: str) -> None:
    value = pins_env().get(key, "")
    assert re.fullmatch(PINS_ENV_SHAPES[key], value), f"pins.env {key}={value!r}"


def test_every_python_harness_has_exactly_one_freeze() -> None:
    assert REQUIREMENT_NAMES == tuple(sorted(PYTHON_HARNESSES)), REQUIREMENT_NAMES


@pytest.mark.parametrize("name", REQUIREMENT_NAMES)
def test_every_line_of_a_harness_freeze_is_an_exact_pin(name: str) -> None:
    """A bare name or a range resolves again at build time, so the venv is no longer the frozen one."""
    lines = pinned_lines(name)
    assert lines, f"requirements-{name}.txt pins nothing"
    loose = [line for line in lines if FREEZE_PIN.fullmatch(line) is None and GIT_PIN.fullmatch(line) is None]
    assert loose == [], loose


@pytest.mark.parametrize("name", REQUIREMENT_NAMES)
def test_a_harness_freeze_is_regenerated_by_freeze_sh_on_the_image_python(name: str) -> None:
    header = (HARNESS / f"requirements-{name}.txt").read_text(encoding="utf-8").splitlines()[0]
    assert "freeze.sh" in header and f"(python{pins_env()['HARNESS_PYTHON']})" in header, header
    assert f"\nfreeze {name} " in (HARNESS / "freeze.sh").read_text(encoding="utf-8"), f"freeze.sh never writes {name}"


def test_the_sweagent_freeze_pins_one_swe_agent_commit() -> None:
    """The images fetch SWE-agent's config and tools at the commit this line names."""
    commits = [line for line in pinned_lines("sweagent") if SWEAGENT_PIN.fullmatch(line)]
    assert len(commits) == 1, commits


@pytest.mark.parametrize("dockerfile", JUDGE_AGENT_DOCKERFILES)
def test_a_judge_agent_image_installs_uv_node_and_the_npm_clis_from_the_pins(dockerfile: str) -> None:
    text = recipe(dockerfile)
    assert "COPY containers/agent/harness/pins.env containers/agent/harness/install_tools.sh" in text
    assert "sh /opt/harness/install_tools.sh /usr/local" in text
    assert ". /opt/harness/pins.env;" in text
    assert (
        "COPY containers/agent/harness/node/package.json containers/agent/harness/node/package-lock.json "
        "/opt/harness/node/" in text
    )
    assert "npm ci " in text


@pytest.mark.parametrize("name", REQUIREMENT_NAMES)
@pytest.mark.parametrize("dockerfile", JUDGE_AGENT_DOCKERFILES)
def test_a_judge_agent_image_copies_each_harness_freeze(dockerfile: str, name: str) -> None:
    assert f"containers/agent/harness/requirements-{name}.txt" in recipe(dockerfile)


@pytest.mark.parametrize("dockerfile", JUDGE_AGENT_DOCKERFILES)
def test_the_venv_install_and_firewall_loops_cover_every_python_harness(dockerfile: str) -> None:
    text = recipe(dockerfile)
    assert '-r "/opt/harness/requirements-${venv}.txt"' in text
    loops = [loop.split() for loop in re.findall(r"for venv in ([^;]+); do", text)]
    assert len(loops) >= 2 and all(sorted(loop) == sorted(PYTHON_HARNESSES) for loop in loops), loops


@pytest.mark.parametrize("name", sorted(PYTHON_HARNESSES))
@pytest.mark.parametrize("dockerfile", JUDGE_AGENT_DOCKERFILES)
def test_a_judge_agent_image_gates_the_import_of_each_python_harness(dockerfile: str, name: str) -> None:
    gate = f"/opt/harness/{name}/bin/python -c '{PYTHON_HARNESSES[name]}'"
    assert gate in recipe(dockerfile), f"{dockerfile} does not run {gate}"


@pytest.mark.parametrize("dockerfile", JUDGE_AGENT_DOCKERFILES)
def test_a_judge_agent_image_gates_every_cli_version_against_package_json(dockerfile: str) -> None:
    text = recipe(dockerfile)
    loop = re.search(r"for pin in ([^;]+); do", text)
    assert loop is not None, f"{dockerfile} has no CLI version gate"
    gated = {pair.partition("=")[2] for pair in loop.group(1).split()}
    assert gated == set(dependencies()), gated
    assert f"dependencies['@anthropic-ai/claude-code']\")\" = {CLAUDE_CODE_VERSION} ]" in text


@pytest.mark.parametrize("dockerfile", IMAGE_DOCKERFILES)
def test_no_image_recipe_fetches_a_tool_version_chosen_on_build_day(dockerfile: str) -> None:
    assert unpinned_installs(recipe(dockerfile)) == []


@pytest.mark.parametrize(
    ("text", "flagged"),
    [
        ("curl -fsSL https://deb.nodesource.com/setup_20.x | bash -", [r"setup_\d+\.x"]),
        ("wget -qO uv.tgz https://github.com/astral-sh/uv/releases/latest/download/uv.tar.gz", ["releases/latest"]),
        ('npm install -g "@anthropic-ai/claude-code"; claude --version', ["@anthropic-ai/claude-code"]),
        ("npm i --global opencode-ai@latest", ["opencode-ai@latest"]),
        ('npm install -g "@anthropic-ai/claude-code@${v}"', ["@anthropic-ai/claude-code@${v}"]),
        ('npm install -g "@openai/codex@0.154.0" opencode-ai@1.18.30', []),
    ],
)
def test_the_unpinned_install_scan_flags_each_floating_fetch(text: str, flagged: list[str]) -> None:
    assert unpinned_installs(text) == flagged
