"""Emit a Numba-compiled version of a numpy kernel.

Numba supports a large subset of numpy plus pure-Python loops; the
translation is simply wrapping the function in ``@numba.njit`` or
``@numba.njit(parallel=True)`` and leaving the body alone.

The ``parallel=True`` variant additionally rewrites the loop variable of
ONE ``range`` for-loop to ``numba.prange`` -- but ONLY a loop a
conservative dependency check can prove has no loop-carried dependency.
A blind rewrite of the first ``range`` loop (the old behaviour) silently
raced a scan / prefix-sum loop (``a[i] = a[i-1] + x[i]``) or a scalar /
same-cell reduction (``out[0] += x[i]``): prange runs the iterations out
of order, so the read of a previously-written cell sees a garbage value.
Correctness wins over speed here -- a loop that cannot be PROVEN
independent is left serial (plain ``range``), never guessed parallel.
"""

import ast
import re
from typing import Literal

Flavor = Literal["njit", "njit_parallel"]

#: Per-flavor njit options (besides ``fastmath``, which is opt-in below).
#: ``fastmath`` is OFF by default: it lets LLVM reassociate reductions and
#: assume no-nan/no-inf, which diverges from numpy's exact semantics (so a
#: faithful translation must not enable it) and additionally miscompiles
#: some gather/while-loop reductions into a SIGSEGV on numba 0.65 + LLVM.
#: Pass ``fastmath=True`` to opt back into the perf-oriented flavor.
_BASE_OPTS = {
    "njit": [],
    "njit_parallel": ["parallel=True"],
}


def emit_numba(numpy_source: str, flavor: Flavor = "njit", fastmath: bool = False, kir=None) -> str:
    """Translate one numpy kernel source into its Numba sibling.

    :param numpy_source: contents of ``<short>_numpy.py``.
    :param flavor: ``"njit"`` for serial, ``"njit_parallel"`` for the
        parallel variant (rewrites bare ``range`` to ``nb.prange``).
    :param fastmath: opt into ``fastmath=True`` (off by default; see
        ``_BASE_OPTS`` for why faithful translation leaves it off).
    :param kir: parsed :class:`KernelIR`; when supplied, ops numba cannot
        type verbatim (batched >=3-D ``@``) are desugared into plain loops.
    :returns: Python source code.
    """
    if flavor not in _BASE_OPTS:
        raise ValueError(f"unknown numba flavor: {flavor!r}")
    if kir is not None:
        from numpyto_common.numpy_desugar import desugar_for_python_backend
        numpy_source = desugar_for_python_backend(numpy_source, kir, backend="numba")
    opts = list(_BASE_OPTS[flavor])
    if fastmath:
        opts.append("fastmath=True")
    opts.append("cache=True")
    decorator = f"@nb.njit({', '.join(opts)})"

    # 1. Make sure ``import numba as nb`` is present.
    out = numpy_source
    if "import numba" not in out:
        out = "import numba as nb\n" + out

    # 2. Inject the decorator on EVERY top-level ``def`` (``(?m)^`` anchors to
    #    column 0, so indented / nested defs are skipped). Decorating only the
    #    first def silently left the real kernel un-njit'd whenever a helper was
    #    defined first (lenet's ``relu`` before ``lenet5``) -- numba then ran the
    #    kernel as plain numpy, a false pass. numba's njit is lazy, so an unused
    #    helper is never compiled; a called one must be njit to be callable from
    #    nopython code, so decorating all top-level defs is both correct and free.
    out = re.sub(r"(?m)^(def\s+\w+\()", f"{decorator}\n\\1", out)

    # 3. Parallel flavor rewrites ONE ``range`` loop to ``nb.prange`` -- the
    #    first (in source order) that ``_loop_is_parallel_safe`` proves carries
    #    no cross-iteration dependency. A loop that fails the check (scan,
    #    scalar/same-cell reduction, index-shifted stencil, data-dependent
    #    scatter) stays serial: prange would reorder its iterations and read a
    #    not-yet-written / already-overwritten cell -> silent miscompile.
    #    The rewrite splices only the ``range`` identifier of the chosen loop
    #    (located via the AST) so the body is otherwise preserved verbatim.
    if flavor == "njit_parallel":
        out = _parallelize_one_range_loop(out)

    header = (f'"""Auto-generated by NumpyToNumba ({flavor}). Decorator added; '
              f'body preserved verbatim."""\n')
    return header + out


def _index_exprs(sub: ast.Subscript) -> list:
    """The per-axis index expressions of a subscript (``A[i, j]`` -> ``[i, j]``)."""
    sl = sub.slice
    return list(sl.elts) if isinstance(sl, ast.Tuple) else [sl]


def _reads_name(node: ast.AST, name: str) -> bool:
    """``True`` when ``name`` is referenced anywhere in ``node``."""
    return any(isinstance(n, ast.Name) and n.id == name for n in ast.walk(node))


def _subscript_idx_safe(sub: ast.Subscript, idx: str) -> bool:
    """A subscript of a WRITTEN array is cross-iteration-safe under ``prange`` on
    ``idx`` iff ``idx`` appears as a BARE index in >=1 axis and never in a derived
    form. That guarantees iteration ``i`` only ever touches the ``i``-th slice, so
    reordering iterations cannot make one read a cell another wrote.

    Refused (returns ``False``):
    * ``idx`` in a shifted / scaled form (``A[i-1]``, ``A[2*i]``) -- a stencil
      read/write straddles iterations.
    * ``idx`` inside a data-dependent index (``A[perm[i]]``) -- unknown pattern.
    * ``idx`` absent entirely (``out[0]``, ``A[j]``) -- a same-cell write every
      iteration (reduction / broadcast) races.
    """
    bare = False
    for e in _index_exprs(sub):
        if isinstance(e, ast.Name) and e.id == idx:
            bare = True
            continue
        if _reads_name(e, idx):
            return False  # idx appears, but not as a bare axis index.
    return bare


def _loop_is_parallel_safe(for_node: ast.For) -> bool:
    """Conservatively decide whether ``for idx in range(...)`` can become a
    ``prange`` without changing results. Errs toward serial: any pattern not
    proven independent returns ``False``."""
    it = for_node.iter
    if not (isinstance(it, ast.Call) and isinstance(it.func, ast.Name) and it.func.id == "range"):
        return False
    if not isinstance(for_node.target, ast.Name):
        return False  # tuple target (``for i, x in enumerate(...)``): not a plain range index.
    idx = for_node.target.id
    body = ast.Module(body=list(for_node.body), type_ignores=[])

    written: set = set()
    for n in ast.walk(body):
        if isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Subscript) and isinstance(t.value, ast.Name):
                    written.add(t.value.id)
                elif isinstance(t, ast.Name) and _reads_name(n.value, t.id):
                    return False  # self-referential carried scalar (``s = s + ...``).
        elif isinstance(n, ast.AugAssign):
            t = n.target
            if isinstance(t, ast.Name):
                return False  # scalar reduction / accumulator (``s += ...``).
            if isinstance(t, ast.Subscript) and isinstance(t.value, ast.Name):
                written.add(t.value.id)

    # Every subscript (read OR write) of an array that is written in the loop must
    # be idx-safe; an augmented write (``A[i] += ...``) is a read+write of ``A[i]``
    # and is covered because its subscript node is walked here too.
    for n in ast.walk(body):
        if isinstance(n, ast.Subscript) and isinstance(n.value, ast.Name) and n.value.id in written:
            if not _subscript_idx_safe(n, idx):
                return False
    return True


def _abs_offset(src: str, lineno: int, col: int) -> int:
    """Absolute character offset of (1-based ``lineno``, 0-based ``col``). The
    source is ASCII, so ``col_offset`` (a UTF-8 byte offset) equals the char offset."""
    lines = src.splitlines(keepends=True)
    return sum(len(line) for line in lines[:lineno - 1]) + col


def _parallelize_one_range_loop(src: str) -> str:
    """Rewrite the ``range`` identifier of the first (source-order) provably
    independent ``range`` for-loop to ``nb.prange``. If none qualify, return
    ``src`` unchanged (fully serial -- correct, just not parallel)."""
    tree = ast.parse(src)
    range_fors = sorted((n for n in ast.walk(tree) if isinstance(n, ast.For) and isinstance(n.iter, ast.Call)
                         and isinstance(n.iter.func, ast.Name) and n.iter.func.id == "range"),
                        key=lambda n: (n.lineno, n.col_offset))
    target = next((f for f in range_fors if _loop_is_parallel_safe(f)), None)
    if target is None:
        return src
    fn = target.iter.func
    off = _abs_offset(src, fn.lineno, fn.col_offset)
    if src[off:off + 5] != "range":
        return src  # position drift (should not happen); leave serial rather than corrupt.
    return src[:off] + "nb.prange" + src[off + 5:]
