#!/usr/bin/env python
# Copyright 2021 ETH Zurich and the HPCAgent-Bench authors.
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render ``requirements/*.txt`` from pyproject, the one place a dependency is declared.

The container images install ``-r requirements/<name>.txt`` and never the project itself: the judge
runs from a repo MOUNTED into the image, so a baked-in install would be a second, stale copy. pip has
no way to install "the extras of a local project, without the project", so those files have to exist
-- but they do not have to be a second hand-maintained list. They are derived here instead.

That divergence was not hypothetical. Before this script, amd.txt and nvidia.txt carried a bare
``pythran`` against pyproject's ``pythran==0.18.1`` -- the pin that exists because 0.19.0 turns
subset_sum into a >600 s hang, then a SIG11 -- and neither declared ``ordered-set`` at all, which
every dace import needs. The CE images installed exactly what those files said.

``--check`` re-renders in memory and diffs; :mod:`tests.test_requirements_cover_project_deps` runs it
so drift fails a test run rather than a container build.
"""
import argparse
import dataclasses
import difflib
import pathlib
import re
import sys
import tomllib
from collections.abc import Sequence

from hpcagent_bench import paths

PYPROJECT = paths.ROOT / "pyproject.toml"

#: A self-reference an extra uses to pull in another extra of the same distribution.
SELF_EXTRA = re.compile(r"^hpcagent_bench\[([A-Za-z0-9._-]+)\]$")


@dataclasses.dataclass(frozen=True, slots=True)
class Rendered:
    """One generated requirements file.

    ``core`` pulls in ``[project] dependencies``; the hardware stacks need them because nothing else
    installs the project's own deps into the CE image. ``groups`` names PEP 735 dependency groups,
    ``includes`` emits ``-r`` lines, and ``options`` are pip option lines that cannot be spelled as a
    PEP 508 requirement and so have no home in pyproject.
    """
    extras: tuple[str, ...]
    core: bool
    groups: tuple[str, ...] = ()
    includes: tuple[str, ...] = ()
    options: tuple[str, ...] = ()
    note: str = ""


#: Every file this script owns. A requirements file NOT listed here is hand-maintained, and
#: :func:`check` says so rather than deleting it: ``optional.txt`` is a two-package convenience split
#: that matches no single extra.
GENERATED: dict[str, Rendered] = {
    "requirements.txt":
    Rendered((),
             core=False,
             groups=("linting", ),
             includes=("requirements/cpu.txt", ),
             note="The CPU runtime stack plus the DEV-ONLY formatters the format-check job and "
             "scripts/check_format.py drive. Equivalent to `pip install -e \'.[cpu]\' --group linting`, "
             "kept because a bare `pip install -r requirements.txt` is what a first-time reader reaches "
             "for."),
    "requirements/cpu.txt":
    Rendered(("cpu", ),
             core=True,
             note="A CPU box. apache-tvm and mpi4py are deliberately absent -- they are the two "
             "baselines with platform install friction, and they live in optional.txt so this "
             "file installs cleanly everywhere, macOS arm64 included."),
    "requirements/nvidia.txt":
    Rendered(("nvidia", ), core=True, options=("--pre", ), note="--pre is required for apache-tvm."),
    "requirements/amd.txt":
    Rendered(("amd", ), core=True, options=("--pre", ), note="--pre is required for apache-tvm."),
    "requirements/hf.txt":
    Rendered(("hf", ),
             core=False,
             note="HuggingFace Dataset export (hpcagent-bench export-hf). Optional: the row builder "
             "and jsonl writer are pure-stdlib; these add the parquet writer and the Hub push."),
    "requirements/harbor.txt":
    Rendered(("harbor", ),
             core=False,
             note="Harbor integration (adapters/hpcagent_bench). Only needed to RUN the benchmark "
             "under Harbor, or to validate a generated task.toml against Harbor's schema. The task "
             "generator and the in-container grader carry no harbor dependency."),
    "requirements/agent-anthropic.txt":
    Rendered(("agent-anthropic", ), core=False, note="Agent backend: the Anthropic API."),
    "requirements/agent-local.txt":
    Rendered(("agent-local", ), core=False, note="Agent backend: a locally hosted transformers model."),
    "requirements/agent-aider.txt":
    Rendered(("agent-aider", ),
             core=False,
             note="Agent backend: aider. It hard-pins numpy==1.26.x against this project's numpy>=2, "
             "which is why it is its own file and its own extra."),
    "requirements/agent-optimas.txt":
    Rendered(("agent-optimas", ), core=False, note="Agent backend: optimas."),
}

HEADER = ("# GENERATED by scripts/sync_requirements.py -- do not edit.\n"
          "# Every name below, and the reason it is here, is declared in pyproject.toml"
          " ({source}).\n"
          "# Regenerate with: python scripts/sync_requirements.py\n")


def resolve(extra: str, extras: dict[str, list[str]], seen: frozenset[str] = frozenset()) -> list[str]:
    """Requirements of ``extra``, with ``hpcagent_bench[other]`` self-references expanded in place.

    Order is declaration order and duplicates are kept; :func:`render` is what dedups, so a name
    stays at the position its first mention gave it.
    """
    if extra in seen:
        raise ValueError(f"extra {extra!r} includes itself: {sorted(seen)}")
    out: list[str] = []
    for requirement in extras[extra]:
        match = SELF_EXTRA.match(requirement.strip())
        if match:
            out.extend(resolve(match.group(1), extras, seen | {extra}))
        else:
            out.append(requirement)
    return out


def render(spec: Rendered, core: Sequence[str], extras: dict[str, list[str]], groups: dict[str, list]) -> str:
    """The full text of one generated requirements file."""
    names: list[str] = list(core) if spec.core else []
    for extra in spec.extras:
        names.extend(resolve(extra, extras))
    for group in spec.groups:
        names.extend(g for g in groups[group] if isinstance(g, str))

    source = ", ".join(("[project] dependencies", ) * spec.core + tuple(f"extra {e!r}" for e in spec.extras) +
                       tuple(f"dependency-group {g!r}" for g in spec.groups))
    lines = [HEADER.format(source=source)]
    if spec.note:
        lines.append("#\n" + "\n".join(f"# {line}" for line in wrap(spec.note)) + "\n")
    lines.extend(f"{option}\n" for option in spec.options)
    lines.extend(f"-r {include}\n" for include in spec.includes)

    emitted: set[str] = set()
    for name in names:
        if name not in emitted:
            emitted.add(name)
            lines.append(f"{name}\n")
    return "".join(lines)


def wrap(text: str, width: int = 96) -> list[str]:
    """Greedy wrap. textwrap would do, but this keeps the one-space-after-period spacing intact."""
    lines: list[str] = []
    current = ""
    for word in text.split(" "):
        if current and len(current) + 1 + len(word) > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}" if current else word
    if current:
        lines.append(current)
    return lines


def rendered_files() -> dict[pathlib.Path, str]:
    """Every generated file's path mapped to the text it should hold."""
    parsed = tomllib.loads(PYPROJECT.read_text())
    project = parsed["project"]
    core = project["dependencies"]
    extras = project["optional-dependencies"]
    groups = parsed["dependency-groups"]
    return {paths.ROOT / name: render(spec, core, extras, groups) for name, spec in GENERATED.items()}


def check() -> list[str]:
    """Unified diffs for every generated file whose on-disk text is stale. Empty means in sync."""
    diffs: list[str] = []
    for path, want in rendered_files().items():
        have = path.read_text() if path.is_file() else ""
        if have != want:
            diffs.append("".join(
                difflib.unified_diff(have.splitlines(True), want.splitlines(True), f"{path.name} (on disk)",
                                     f"{path.name} (from pyproject)")))
    return diffs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="diff instead of writing; non-zero exit when stale")
    args = parser.parse_args()

    if args.check:
        diffs = check()
        for diff in diffs:
            sys.stdout.write(diff)
        return 1 if diffs else 0

    for path, text in rendered_files().items():
        path.write_text(text)
        print(f"wrote {path.relative_to(paths.ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
