#!/usr/bin/env bash
# Copyright 2021 ETH Zurich and the HPCAgent-Bench authors.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Container acceptance: does a freshly BUILT image actually serve?
#
# The build gates prove the image assembles and imports -- an import is not a kernel launch and a
# launch is not a served token, which is why every build script says NOT VERIFIED at the end. This
# closes that gap by pointing the EXISTING inference smokes at the candidate .sqsh instead of the
# deployed one: an EDF is written per candidate and the smoke runs unchanged, so a pass here means
# the same thing a pass on the deployed image means.
#
#   ./smoke-new-images.sh                 # every candidate that exists
#   ./smoke-new-images.sh sglang          # just one
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

SCRATCH="${SCRATCH:?}"
IMAGES="${SCRATCH}/ce-images"
EDF_DIR="${HOME}/.edf"
SMOKES="../ce-images/inference"
mkdir -p "${EDF_DIR}"

# candidate .sqsh -> the smoke that knows how to drive that engine
declare -A SMOKE=(
  [sglang]="${SMOKES}/smoke-kimi-sglang.sbatch"
  [vllm]="${SMOKES}/smoke-kimi-eager-pg.sbatch"
  [vllm-0271]="${SMOKES}/smoke-kimi-eager-pg.sbatch"
)
declare -A SQSH=(
  [sglang]="${IMAGES}/optarena-sglang-candidate.sqsh"
  [vllm]="${IMAGES}/optarena-vllm-candidate.sqsh"
  [vllm-0271]="${IMAGES}/optarena-vllm-0271-candidate.sqsh"
)

candidates=("$@")
[[ ${#candidates[@]} -eq 0 ]] && candidates=(sglang vllm vllm-0271)
for name in "${candidates[@]}"; do
  sqsh="${SQSH[${name}]:-}"
  smoke="${SMOKE[${name}]:-}"
  [[ -n "${sqsh}" ]] || { echo "unknown candidate: ${name}" >&2; exit 2; }
  if [[ ! -f "${sqsh}" ]]; then
    printf '%-12s SKIP  no candidate image at %s\n' "${name}" "${sqsh}"
    continue
  fi
  # The digest sidecar is what makes a pass attributable to a BUILD rather than to a file name;
  # a candidate without one was not written by build.sh and is not what we mean to accept.
  test -s "${sqsh}.image-digest" || { echo "${name}: no .image-digest beside ${sqsh}" >&2; exit 1; }
  edf="${EDF_DIR}/candidate-${name}.toml"
  {
    printf '# GENERATED by smoke-new-images.sh -- candidate acceptance only, never a campaign EDF.\n'
    printf '# image digest: %s\n' "$(cat "${sqsh}.image-digest")"
    printf 'image = "%s"\n\n' "${sqsh}"
    printf 'mounts = [\n  "/capstor:/capstor",\n  "/iopsstor:/iopsstor"\n]\n'
  } > "${edf}"
  printf '%-12s EDF=%s\n' "${name}" "${edf}"
  EDF="${edf}" sbatch --job-name="smoke-candidate-${name}" "${smoke}"
done
