#!/usr/bin/env bash
# Copyright 2021 ETH Zurich and the HPCAgent-Bench authors.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Container acceptance: does a freshly BUILT image actually serve?
#
# The build gates prove the image assembles and imports -- an import is not a kernel launch and a
# launch is not a served token, which is why every build script says NOT VERIFIED at the end. This
# closes that gap by pointing the EXISTING inference smokes at the candidate .sqsh instead of the
# deployed one: an EDF is written per candidate and the smoke runs unchanged, so a pass here means
# the same thing a pass on the deployed image means.
#
#   ./smoke-new-images.sh                 # every candidate that exists
#   ./smoke-new-images.sh sglang          # just one
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

SCRATCH="${SCRATCH:?}"
IMAGES="${SCRATCH}/ce-images"
EDF_DIR="${HOME}/.edf"
SMOKES="../ce-images/inference"
mkdir -p "${EDF_DIR}"

# candidate .sqsh -> the smoke that knows how to drive that engine
declare -A SMOKE=(
  [sglang]="${SMOKES}/smoke-kimi-sglang.sbatch"
  [vllm]="${SMOKES}/smoke-kimi-eager-pg.sbatch"
  [vllm-0271]="${SMOKES}/smoke-kimi-eager-pg.sbatch"
)
declare -A SQSH=(
  [sglang]="${IMAGES}/optarena-sglang-candidate.sqsh"
  [vllm]="${IMAGES}/optarena-vllm-candidate.sqsh"
  [vllm-0271]="${IMAGES}/optarena-vllm-0271-candidate.sqsh"
)
# What each engine is ACCEPTED on is the model the campaign actually serves from it: kimi on
# sglang, gpt-oss on vLLM. Running kimi against a vLLM candidate measures a configuration we
# already know is not viable (4.1 s per forward pass at campaign context) over 4 nodes, so it
# would burn the allocation to reproduce a dead end rather than accept the image. The oss control
# is one node at pp=1 and is the run smoke-kimi-eager-pg.sbatch documents for exactly this.
declare -A NODES=([sglang]=2 [vllm]=1 [vllm-0271]=1)
declare -A MODEL=([vllm]=openai/gpt-oss-120b [vllm-0271]=openai/gpt-oss-120b)

candidates=("$@")
[[ ${#candidates[@]} -eq 0 ]] && candidates=(sglang vllm vllm-0271)
for name in "${candidates[@]}"; do
  sqsh="${SQSH[${name}]:-}"
  smoke="${SMOKE[${name}]:-}"
  [[ -n "${sqsh}" ]] || { echo "unknown candidate: ${name}" >&2; exit 2; }
  if [[ ! -f "${sqsh}" ]]; then
    printf '%-12s SKIP  no candidate image at %s\n' "${name}" "${sqsh}"
    continue
  fi
  # The digest sidecar is what makes a pass attributable to a BUILD rather than to a file name;
  # a candidate without one was not written by build.sh and is not what we mean to accept.
  test -s "${sqsh}.image-digest" || { echo "${name}: no .image-digest beside ${sqsh}" >&2; exit 1; }
  edf="${EDF_DIR}/candidate-${name}.toml"
  {
    printf '# GENERATED by smoke-new-images.sh -- candidate acceptance only, never a campaign EDF.\n'
    printf '# image digest: %s\n' "$(cat "${sqsh}.image-digest")"
    printf 'image = "%s"\n\n' "${sqsh}"
    printf 'mounts = [\n  "/capstor:/capstor",\n  "/iopsstor:/iopsstor"\n]\n'
  } > "${edf}"
  printf '%-12s EDF=%s\n' "${name}" "${edf}"
  # PG_PATCH_DIR: the eager-PG smoke insists on an EXTERNAL sitecustomize.py, from the era when the
  # patch was injected at run time. The candidate images bake it in (vllm/Dockerfile COPYs it to
  # /opt/vllm-eager-pg), so this only satisfies the smoke's precondition with the identical file
  # rather than changing what is tested; without it the job exits in one second (620856).
  # Logs to scratch, not to logs/ under the submit directory -- that is the source tree.
  # Parsers are model-specific and the serve flags carry spaces, so they travel as environment
  # (sbatch propagates it) rather than through --export, which splits on commas.
  oss=()
  if [[ -n "${MODEL[${name}]:-}" ]]; then
    oss=(MODEL_REPO="${MODEL[${name}]}" TOOL_PARSER=openai REASONING_PARSER=openai_gptoss
         EXTRA_SERVE_ARGS="--dtype bfloat16")
  fi
  # TUNED_MOE_DIR defaults to <submit dir>/moe-configs, and this driver submits from HERE, where
  # there is no such folder -- an empty one reads as "tuned" and is how a smoke measures the
  # untuned ceiling and calls it a result. Name the real folder. E=128,N=192 is the gpt-oss shape.
  env "${oss[@]}" \
  TUNED_MOE_DIR="${PWD}/../ce-images/inference/moe-configs" \
  PG_PATCH_DIR="${PWD}/../ce-images/inference/external-eager-pg-patch" \
  EDF="${edf}" sbatch --job-name="smoke-candidate-${name}" \
    --nodes="${NODES[${name}]}" \
    --output="${SCRATCH}/ce-images/logs/smoke-candidate-${name}-%j.out" \
    --error="${SCRATCH}/ce-images/logs/smoke-candidate-${name}-%j.out" "${smoke}"
done
